import random as R; import time as T
install = open("install.txt").readlines()
print("downloading deb packages...")
T.sleep(2)
print("deb packages downloaded")
T.sleep(1)
print("initializing deb packages...")
T.sleep(2)
print("running upacker...")
T.sleep(2)
print("ready for installation")
T.sleep(0.5)
choice = R.choice(install).strip()
print("")
print("deb install", choice)